# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Evolutionary Anthropology Society
description: > # this means to ignore newlines until "baseurl:"
    EAS is a community of scholars interested in applying 
    modern evolutionary theory to the analysis of human biology, 
    behavior, and culture. As a part of the American Anthropological 
    Association, EAS is interested in helping students present their 
    research at our annual meeting and building ties across scientific
    sub-disciplines within the diverse field of anthropology.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter: evanthsociety
facebook: https://www.facebook.com/groups/evanthsociety/

encoding: utf-8

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
